services:
  # only here for building/testing purposes
  k3s-lab:
    profiles:
      - lab-client
    networks:
      - k3s
    build: 
      context: infra/lab-container
      additional_contexts:
        lab: lab
    image: devinchristianson/k3dlab:4.2.0
    user: root
    environment:
      - USERNAME=testuser
      - ENVIRONMENT=k3s
      - DOMAIN=${DOMAIN}
  k3d-http:
    profiles:
      - k3s
    runtime: runc
    build: 
      context: infra/k3d-http
    environment:
      - DOMAIN=k3s.${DOMAIN}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./infra/k3d-http/k3dconfig.yml:/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
      - k3s
networks:
  k3s: